title: Eric C. Anderson's Work-life 
tagline: Open research with GitHub
owner: Eric C. Anderson
link: https://github.com/eriqande/eriqande.github.com
copyright: US Federal Gov't Work. Public Domain.
#url: http://eriqande.github.io
baseurl: /
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis"]
exclude: [README.md,Rmd,R-convert-rmd,_worklogs/work-log-template.md]

collections:
  worklogs:
    output: true