title: Eric C. Anderson's Work-life 
tagline: Open research with GitHub
owner: Eric C. Anderson
link: https://github.com/eriqande/eriqande.githum.com
copyright: US Federal Gov't Work. Public Domain.


pygments: true
permalink: '/:title'
markdown: rdiscount

exclude: [README.md]

